package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"

	"github.com/roderm/graphql-gateway-examples/example-1/accounts/graph/data"
	"github.com/roderm/graphql-gateway-examples/example-1/accounts/graph/generated"
)

// FindAWSUserByID is the resolver for the findAWSUserByID field.
func (r *entityResolver) FindAWSUserByID(ctx context.Context, id string) (*data.AWSUser, error) {
	return data.User2, nil
}

// FindGitHubUserByID is the resolver for the findGitHubUserByID field.
func (r *entityResolver) FindGitHubUserByID(ctx context.Context, id string) (*data.GitHubUser, error) {
	return data.User1, nil
}

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (data.User, error) {
	panic(fmt.Errorf("not implemented: FindUserByID - findUserByID"))
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
